//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

using System;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;
using FaPA.Core.FaPa.SignatureFPA;

namespace FaPaTets.FatturaPa.FatturaPa_11
{
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    [XmlRoot( "FatturaElettronica", Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1", IsNullable = false )]
    public partial class FatturaElettronicaType_V11_Test
    {

        private FatturaElettronicaHeaderType fatturaElettronicaHeaderField;

        private FatturaElettronicaBodyType[] fatturaElettronicaBodyField;

        private VersioneSchemaType versioneField;

        
        
        public FatturaElettronicaHeaderType FatturaElettronicaHeader
        {
            get
            {
                return this.fatturaElettronicaHeaderField;
            }
            set
            {
                this.fatturaElettronicaHeaderField = value;
            }
        }

        
        [XmlElement( "FatturaElettronicaBody", Form = XmlSchemaForm.Unqualified )]
        public FatturaElettronicaBodyType[] FatturaElettronicaBody
        {
            get
            {
                return this.fatturaElettronicaBodyField;
            }
            set
            {
                this.fatturaElettronicaBodyField = value;
            }
        }

        private SignatureType signatureField;
        
        [XmlElement( Namespace = "http://www.w3.org/2000/09/xmldsig#" )]
        public SignatureType Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }


        
        [XmlAttribute()]
        public VersioneSchemaType versione
        {
            get
            {
                return this.versioneField;
            }
            set
            {
                this.versioneField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class FatturaElettronicaHeaderType
    {

        private DatiTrasmissioneType datiTrasmissioneField;

        private CedentePrestatoreType cedentePrestatoreField;

        private RappresentanteFiscaleType rappresentanteFiscaleField;

        private CessionarioCommittenteType cessionarioCommittenteField;

        private TerzoIntermediarioSoggettoEmittenteType terzoIntermediarioOSoggettoEmittenteField;

        private SoggettoEmittenteType soggettoEmittenteField;

        private bool soggettoEmittenteFieldSpecified;

        
        
        public DatiTrasmissioneType DatiTrasmissione
        {
            get
            {
                return this.datiTrasmissioneField;
            }
            set
            {
                this.datiTrasmissioneField = value;
            }
        }

        
        
        public CedentePrestatoreType CedentePrestatore
        {
            get
            {
                return this.cedentePrestatoreField;
            }
            set
            {
                this.cedentePrestatoreField = value;
            }
        }

        
        
        public RappresentanteFiscaleType RappresentanteFiscale
        {
            get
            {
                return this.rappresentanteFiscaleField;
            }
            set
            {
                this.rappresentanteFiscaleField = value;
            }
        }

        
        
        public CessionarioCommittenteType CessionarioCommittente
        {
            get
            {
                return this.cessionarioCommittenteField;
            }
            set
            {
                this.cessionarioCommittenteField = value;
            }
        }

        
        
        public TerzoIntermediarioSoggettoEmittenteType TerzoIntermediarioOSoggettoEmittente
        {
            get
            {
                return this.terzoIntermediarioOSoggettoEmittenteField;
            }
            set
            {
                this.terzoIntermediarioOSoggettoEmittenteField = value;
            }
        }

        
        
        public SoggettoEmittenteType SoggettoEmittente
        {
            get
            {
                return this.soggettoEmittenteField;
            }
            set
            {
                this.soggettoEmittenteField = value;
            }
        }

        
        [XmlIgnore()]
        public bool SoggettoEmittenteSpecified
        {
            get
            {
                return this.soggettoEmittenteFieldSpecified;
            }
            set
            {
                this.soggettoEmittenteFieldSpecified = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiTrasmissioneType
    {

        private IdFiscaleType idTrasmittenteField;

        private string progressivoInvioField;

        private FormatoTrasmissioneType formatoTrasmissioneField;

        private string codiceDestinatarioField;

        private ContattiTrasmittenteType contattiTrasmittenteField;

        
        
        public IdFiscaleType IdTrasmittente
        {
            get
            {
                return this.idTrasmittenteField;
            }
            set
            {
                this.idTrasmittenteField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string ProgressivoInvio
        {
            get
            {
                return this.progressivoInvioField;
            }
            set
            {
                this.progressivoInvioField = value;
            }
        }

        
        
        public FormatoTrasmissioneType FormatoTrasmissione
        {
            get
            {
                return this.formatoTrasmissioneField;
            }
            set
            {
                this.formatoTrasmissioneField = value;
            }
        }

        
        
        public string CodiceDestinatario
        {
            get
            {
                return this.codiceDestinatarioField;
            }
            set
            {
                this.codiceDestinatarioField = value;
            }
        }

        
        
        public ContattiTrasmittenteType ContattiTrasmittente
        {
            get
            {
                return this.contattiTrasmittenteField;
            }
            set
            {
                this.contattiTrasmittenteField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class IdFiscaleType
    {

        private string idPaeseField;

        private string idCodiceField;

        
        
        public string IdPaese
        {
            get
            {
                return this.idPaeseField;
            }
            set
            {
                this.idPaeseField = value;
            }
        }

        
        
        public string IdCodice
        {
            get
            {
                return this.idCodiceField;
            }
            set
            {
                this.idCodiceField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class AllegatiType
    {

        private string nomeAttachmentField;

        private string algoritmoCompressioneField;

        private string formatoAttachmentField;

        private string descrizioneAttachmentField;

        private byte[] attachmentField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NomeAttachment
        {
            get
            {
                return this.nomeAttachmentField;
            }
            set
            {
                this.nomeAttachmentField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string AlgoritmoCompressione
        {
            get
            {
                return this.algoritmoCompressioneField;
            }
            set
            {
                this.algoritmoCompressioneField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string FormatoAttachment
        {
            get
            {
                return this.formatoAttachmentField;
            }
            set
            {
                this.formatoAttachmentField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string DescrizioneAttachment
        {
            get
            {
                return this.descrizioneAttachmentField;
            }
            set
            {
                this.descrizioneAttachmentField = value;
            }
        }

        
        [XmlElement(  DataType = "base64Binary" )]
        public byte[] Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DettaglioPagamentoType
    {

        private string beneficiarioField;

        private ModalitaPagamentoType modalitaPagamentoField;

        private DateTime dataRiferimentoTerminiPagamentoField;

        private bool dataRiferimentoTerminiPagamentoFieldSpecified;

        private string giorniTerminiPagamentoField;

        private DateTime dataScadenzaPagamentoField;

        private bool dataScadenzaPagamentoFieldSpecified;

        private decimal importoPagamentoField;

        private string codUfficioPostaleField;

        private string cognomeQuietanzanteField;

        private string nomeQuietanzanteField;

        private string cFQuietanzanteField;

        private string titoloQuietanzanteField;

        private string istitutoFinanziarioField;

        private string iBANField;

        private string aBIField;

        private string cABField;

        private string bICField;

        private decimal scontoPagamentoAnticipatoField;

        private bool scontoPagamentoAnticipatoFieldSpecified;

        private DateTime dataLimitePagamentoAnticipatoField;

        private bool dataLimitePagamentoAnticipatoFieldSpecified;

        private decimal penalitaPagamentiRitardatiField;

        private bool penalitaPagamentiRitardatiFieldSpecified;

        private DateTime dataDecorrenzaPenaleField;

        private bool dataDecorrenzaPenaleFieldSpecified;

        private string codicePagamentoField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Beneficiario
        {
            get
            {
                return this.beneficiarioField;
            }
            set
            {
                this.beneficiarioField = value;
            }
        }

        
        
        public ModalitaPagamentoType ModalitaPagamento
        {
            get
            {
                return this.modalitaPagamentoField;
            }
            set
            {
                this.modalitaPagamentoField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataRiferimentoTerminiPagamento
        {
            get
            {
                return this.dataRiferimentoTerminiPagamentoField;
            }
            set
            {
                this.dataRiferimentoTerminiPagamentoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataRiferimentoTerminiPagamentoSpecified
        {
            get
            {
                return this.dataRiferimentoTerminiPagamentoFieldSpecified;
            }
            set
            {
                this.dataRiferimentoTerminiPagamentoFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "integer" )]
        public string GiorniTerminiPagamento
        {
            get
            {
                return this.giorniTerminiPagamentoField;
            }
            set
            {
                this.giorniTerminiPagamentoField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataScadenzaPagamento
        {
            get
            {
                return this.dataScadenzaPagamentoField;
            }
            set
            {
                this.dataScadenzaPagamentoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataScadenzaPagamentoSpecified
        {
            get
            {
                return this.dataScadenzaPagamentoFieldSpecified;
            }
            set
            {
                this.dataScadenzaPagamentoFieldSpecified = value;
            }
        }

        
        
        public decimal ImportoPagamento
        {
            get
            {
                return this.importoPagamentoField;
            }
            set
            {
                this.importoPagamentoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodUfficioPostale
        {
            get
            {
                return this.codUfficioPostaleField;
            }
            set
            {
                this.codUfficioPostaleField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CognomeQuietanzante
        {
            get
            {
                return this.cognomeQuietanzanteField;
            }
            set
            {
                this.cognomeQuietanzanteField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NomeQuietanzante
        {
            get
            {
                return this.nomeQuietanzanteField;
            }
            set
            {
                this.nomeQuietanzanteField = value;
            }
        }

        
        
        public string CFQuietanzante
        {
            get
            {
                return this.cFQuietanzanteField;
            }
            set
            {
                this.cFQuietanzanteField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string TitoloQuietanzante
        {
            get
            {
                return this.titoloQuietanzanteField;
            }
            set
            {
                this.titoloQuietanzanteField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string IstitutoFinanziario
        {
            get
            {
                return this.istitutoFinanziarioField;
            }
            set
            {
                this.istitutoFinanziarioField = value;
            }
        }

        
        
        public string IBAN
        {
            get
            {
                return this.iBANField;
            }
            set
            {
                this.iBANField = value;
            }
        }

        
        
        public string ABI
        {
            get
            {
                return this.aBIField;
            }
            set
            {
                this.aBIField = value;
            }
        }

        
        
        public string CAB
        {
            get
            {
                return this.cABField;
            }
            set
            {
                this.cABField = value;
            }
        }

        
        
        public string BIC
        {
            get
            {
                return this.bICField;
            }
            set
            {
                this.bICField = value;
            }
        }

        
        
        public decimal ScontoPagamentoAnticipato
        {
            get
            {
                return this.scontoPagamentoAnticipatoField;
            }
            set
            {
                this.scontoPagamentoAnticipatoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ScontoPagamentoAnticipatoSpecified
        {
            get
            {
                return this.scontoPagamentoAnticipatoFieldSpecified;
            }
            set
            {
                this.scontoPagamentoAnticipatoFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataLimitePagamentoAnticipato
        {
            get
            {
                return this.dataLimitePagamentoAnticipatoField;
            }
            set
            {
                this.dataLimitePagamentoAnticipatoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataLimitePagamentoAnticipatoSpecified
        {
            get
            {
                return this.dataLimitePagamentoAnticipatoFieldSpecified;
            }
            set
            {
                this.dataLimitePagamentoAnticipatoFieldSpecified = value;
            }
        }

        
        
        public decimal PenalitaPagamentiRitardati
        {
            get
            {
                return this.penalitaPagamentiRitardatiField;
            }
            set
            {
                this.penalitaPagamentiRitardatiField = value;
            }
        }

        
        [XmlIgnore()]
        public bool PenalitaPagamentiRitardatiSpecified
        {
            get
            {
                return this.penalitaPagamentiRitardatiFieldSpecified;
            }
            set
            {
                this.penalitaPagamentiRitardatiFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataDecorrenzaPenale
        {
            get
            {
                return this.dataDecorrenzaPenaleField;
            }
            set
            {
                this.dataDecorrenzaPenaleField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataDecorrenzaPenaleSpecified
        {
            get
            {
                return this.dataDecorrenzaPenaleFieldSpecified;
            }
            set
            {
                this.dataDecorrenzaPenaleFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodicePagamento
        {
            get
            {
                return this.codicePagamentoField;
            }
            set
            {
                this.codicePagamentoField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum ModalitaPagamentoType
    {

        
        MP01,

        
        MP02,

        
        MP03,

        
        MP04,

        
        MP05,

        
        MP06,

        
        MP07,

        
        MP08,

        
        MP09,

        
        MP10,

        
        MP11,

        
        MP12,

        
        MP13,

        
        MP14,

        
        MP15,

        
        MP16,

        
        MP17,

        
        MP18,

        
        MP19,

        
        MP20,

        
        MP21,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiPagamentoType
    {

        private CondizioniPagamentoType condizioniPagamentoField;

        private DettaglioPagamentoType[] dettaglioPagamentoField;

        
        
        public CondizioniPagamentoType CondizioniPagamento
        {
            get
            {
                return this.condizioniPagamentoField;
            }
            set
            {
                this.condizioniPagamentoField = value;
            }
        }

        
        [XmlElement( "DettaglioPagamento", Form = XmlSchemaForm.Unqualified )]
        public DettaglioPagamentoType[] DettaglioPagamento
        {
            get
            {
                return this.dettaglioPagamentoField;
            }
            set
            {
                this.dettaglioPagamentoField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum CondizioniPagamentoType
    {

        
        TP01,

        
        TP02,

        
        TP03,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiVeicoliType
    {

        private DateTime dataField;

        private string totalePercorsoField;

        
        [XmlElement(  DataType = "date" )]
        public DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string TotalePercorso
        {
            get
            {
                return this.totalePercorsoField;
            }
            set
            {
                this.totalePercorsoField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiRiepilogoType
    {

        private decimal aliquotaIVAField;

        private NaturaType naturaField;

        private bool naturaFieldSpecified;

        private decimal speseAccessorieField;

        private bool speseAccessorieFieldSpecified;

        private decimal arrotondamentoField;

        private bool arrotondamentoFieldSpecified;

        private decimal imponibileImportoField;

        private decimal impostaField;

        private EsigibilitaIVAType esigibilitaIVAField;

        private bool esigibilitaIVAFieldSpecified;

        private string riferimentoNormativoField;

        
        
        public decimal AliquotaIVA
        {
            get
            {
                return this.aliquotaIVAField;
            }
            set
            {
                this.aliquotaIVAField = value;
            }
        }

        
        
        public NaturaType Natura
        {
            get
            {
                return this.naturaField;
            }
            set
            {
                this.naturaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool NaturaSpecified
        {
            get
            {
                return this.naturaFieldSpecified;
            }
            set
            {
                this.naturaFieldSpecified = value;
            }
        }

        
        
        public decimal SpeseAccessorie
        {
            get
            {
                return this.speseAccessorieField;
            }
            set
            {
                this.speseAccessorieField = value;
            }
        }

        
        [XmlIgnore()]
        public bool SpeseAccessorieSpecified
        {
            get
            {
                return this.speseAccessorieFieldSpecified;
            }
            set
            {
                this.speseAccessorieFieldSpecified = value;
            }
        }

        
        
        public decimal Arrotondamento
        {
            get
            {
                return this.arrotondamentoField;
            }
            set
            {
                this.arrotondamentoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ArrotondamentoSpecified
        {
            get
            {
                return this.arrotondamentoFieldSpecified;
            }
            set
            {
                this.arrotondamentoFieldSpecified = value;
            }
        }

        
        
        public decimal ImponibileImporto
        {
            get
            {
                return this.imponibileImportoField;
            }
            set
            {
                this.imponibileImportoField = value;
            }
        }

        
        
        public decimal Imposta
        {
            get
            {
                return this.impostaField;
            }
            set
            {
                this.impostaField = value;
            }
        }

        
        
        public EsigibilitaIVAType EsigibilitaIVA
        {
            get
            {
                return this.esigibilitaIVAField;
            }
            set
            {
                this.esigibilitaIVAField = value;
            }
        }

        
        [XmlIgnore()]
        public bool EsigibilitaIVASpecified
        {
            get
            {
                return this.esigibilitaIVAFieldSpecified;
            }
            set
            {
                this.esigibilitaIVAFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string RiferimentoNormativo
        {
            get
            {
                return this.riferimentoNormativoField;
            }
            set
            {
                this.riferimentoNormativoField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum NaturaType
    {

        
        N1,

        
        N2,

        
        N3,

        
        N4,

        
        N5,

        
        N6,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum EsigibilitaIVAType
    {

        
        D,

        
        I,

        
        S,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class AltriDatiGestionaliType
    {

        private string tipoDatoField;

        private string riferimentoTestoField;

        private decimal riferimentoNumeroField;

        private bool riferimentoNumeroFieldSpecified;

        private DateTime riferimentoDataField;

        private bool riferimentoDataFieldSpecified;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string TipoDato
        {
            get
            {
                return this.tipoDatoField;
            }
            set
            {
                this.tipoDatoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string RiferimentoTesto
        {
            get
            {
                return this.riferimentoTestoField;
            }
            set
            {
                this.riferimentoTestoField = value;
            }
        }

        
        
        public decimal RiferimentoNumero
        {
            get
            {
                return this.riferimentoNumeroField;
            }
            set
            {
                this.riferimentoNumeroField = value;
            }
        }

        
        [XmlIgnore()]
        public bool RiferimentoNumeroSpecified
        {
            get
            {
                return this.riferimentoNumeroFieldSpecified;
            }
            set
            {
                this.riferimentoNumeroFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime RiferimentoData
        {
            get
            {
                return this.riferimentoDataField;
            }
            set
            {
                this.riferimentoDataField = value;
            }
        }

        
        [XmlIgnore()]
        public bool RiferimentoDataSpecified
        {
            get
            {
                return this.riferimentoDataFieldSpecified;
            }
            set
            {
                this.riferimentoDataFieldSpecified = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class CodiceArticoloType
    {

        private string codiceTipoField;

        private string codiceValoreField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodiceTipo
        {
            get
            {
                return this.codiceTipoField;
            }
            set
            {
                this.codiceTipoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodiceValore
        {
            get
            {
                return this.codiceValoreField;
            }
            set
            {
                this.codiceValoreField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DettaglioLineeType
    {

        private string numeroLineaField;

        private TipoCessionePrestazioneType tipoCessionePrestazioneField;

        private bool tipoCessionePrestazioneFieldSpecified;

        private CodiceArticoloType[] codiceArticoloField;

        private string descrizioneField;

        private decimal quantitaField;

        private bool quantitaFieldSpecified;

        private string unitaMisuraField;

        private DateTime dataInizioPeriodoField;

        private bool dataInizioPeriodoFieldSpecified;

        private DateTime dataFinePeriodoField;

        private bool dataFinePeriodoFieldSpecified;

        private decimal prezzoUnitarioField;

        private ScontoMaggiorazioneType[] scontoMaggiorazioneField;

        private decimal prezzoTotaleField;

        private decimal aliquotaIVAField;

        private RitenutaType ritenutaField;

        private bool ritenutaFieldSpecified;

        private NaturaType naturaField;

        private bool naturaFieldSpecified;

        private string riferimentoAmministrazioneField;

        private AltriDatiGestionaliType[] altriDatiGestionaliField;

        
        [XmlElement(  DataType = "integer" )]
        public string NumeroLinea
        {
            get
            {
                return this.numeroLineaField;
            }
            set
            {
                this.numeroLineaField = value;
            }
        }

        
        
        public TipoCessionePrestazioneType TipoCessionePrestazione
        {
            get
            {
                return this.tipoCessionePrestazioneField;
            }
            set
            {
                this.tipoCessionePrestazioneField = value;
            }
        }

        
        [XmlIgnore()]
        public bool TipoCessionePrestazioneSpecified
        {
            get
            {
                return this.tipoCessionePrestazioneFieldSpecified;
            }
            set
            {
                this.tipoCessionePrestazioneFieldSpecified = value;
            }
        }

        
        [XmlElement( "CodiceArticolo", Form = XmlSchemaForm.Unqualified )]
        public CodiceArticoloType[] CodiceArticolo
        {
            get
            {
                return this.codiceArticoloField;
            }
            set
            {
                this.codiceArticoloField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        
        
        public decimal Quantita
        {
            get
            {
                return this.quantitaField;
            }
            set
            {
                this.quantitaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool QuantitaSpecified
        {
            get
            {
                return this.quantitaFieldSpecified;
            }
            set
            {
                this.quantitaFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string UnitaMisura
        {
            get
            {
                return this.unitaMisuraField;
            }
            set
            {
                this.unitaMisuraField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataInizioPeriodo
        {
            get
            {
                return this.dataInizioPeriodoField;
            }
            set
            {
                this.dataInizioPeriodoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataInizioPeriodoSpecified
        {
            get
            {
                return this.dataInizioPeriodoFieldSpecified;
            }
            set
            {
                this.dataInizioPeriodoFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataFinePeriodo
        {
            get
            {
                return this.dataFinePeriodoField;
            }
            set
            {
                this.dataFinePeriodoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataFinePeriodoSpecified
        {
            get
            {
                return this.dataFinePeriodoFieldSpecified;
            }
            set
            {
                this.dataFinePeriodoFieldSpecified = value;
            }
        }

        
        
        public decimal PrezzoUnitario
        {
            get
            {
                return this.prezzoUnitarioField;
            }
            set
            {
                this.prezzoUnitarioField = value;
            }
        }

        
        [XmlElement( "ScontoMaggiorazione", Form = XmlSchemaForm.Unqualified )]
        public ScontoMaggiorazioneType[] ScontoMaggiorazione
        {
            get
            {
                return this.scontoMaggiorazioneField;
            }
            set
            {
                this.scontoMaggiorazioneField = value;
            }
        }

        
        
        public decimal PrezzoTotale
        {
            get
            {
                return this.prezzoTotaleField;
            }
            set
            {
                this.prezzoTotaleField = value;
            }
        }

        
        
        public decimal AliquotaIVA
        {
            get
            {
                return this.aliquotaIVAField;
            }
            set
            {
                this.aliquotaIVAField = value;
            }
        }

        
        
        public RitenutaType Ritenuta
        {
            get
            {
                return this.ritenutaField;
            }
            set
            {
                this.ritenutaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool RitenutaSpecified
        {
            get
            {
                return this.ritenutaFieldSpecified;
            }
            set
            {
                this.ritenutaFieldSpecified = value;
            }
        }

        
        
        public NaturaType Natura
        {
            get
            {
                return this.naturaField;
            }
            set
            {
                this.naturaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool NaturaSpecified
        {
            get
            {
                return this.naturaFieldSpecified;
            }
            set
            {
                this.naturaFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string RiferimentoAmministrazione
        {
            get
            {
                return this.riferimentoAmministrazioneField;
            }
            set
            {
                this.riferimentoAmministrazioneField = value;
            }
        }

        
        [XmlElement( "AltriDatiGestionali", Form = XmlSchemaForm.Unqualified )]
        public AltriDatiGestionaliType[] AltriDatiGestionali
        {
            get
            {
                return this.altriDatiGestionaliField;
            }
            set
            {
                this.altriDatiGestionaliField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum TipoCessionePrestazioneType
    {

        
        SC,

        
        PR,

        
        AB,

        
        AC,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class ScontoMaggiorazioneType
    {

        private TipoScontoMaggiorazioneType tipoField;

        private decimal percentualeField;

        private bool percentualeFieldSpecified;

        private decimal importoField;

        private bool importoFieldSpecified;

        
        
        public TipoScontoMaggiorazioneType Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        
        
        public decimal Percentuale
        {
            get
            {
                return this.percentualeField;
            }
            set
            {
                this.percentualeField = value;
            }
        }

        
        [XmlIgnore()]
        public bool PercentualeSpecified
        {
            get
            {
                return this.percentualeFieldSpecified;
            }
            set
            {
                this.percentualeFieldSpecified = value;
            }
        }

        
        
        public decimal Importo
        {
            get
            {
                return this.importoField;
            }
            set
            {
                this.importoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ImportoSpecified
        {
            get
            {
                return this.importoFieldSpecified;
            }
            set
            {
                this.importoFieldSpecified = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum TipoScontoMaggiorazioneType
    {

        
        SC,

        
        MG,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum RitenutaType
    {

        
        SI,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiBeniServiziType
    {

        private DettaglioLineeType[] dettaglioLineeField;

        private DatiRiepilogoType[] datiRiepilogoField;

        
        [XmlElement( "DettaglioLinee", Form = XmlSchemaForm.Unqualified )]
        public DettaglioLineeType[] DettaglioLinee
        {
            get
            {
                return this.dettaglioLineeField;
            }
            set
            {
                this.dettaglioLineeField = value;
            }
        }

        
        [XmlElement( "DatiRiepilogo", Form = XmlSchemaForm.Unqualified )]
        public DatiRiepilogoType[] DatiRiepilogo
        {
            get
            {
                return this.datiRiepilogoField;
            }
            set
            {
                this.datiRiepilogoField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class FatturaPrincipaleType
    {

        private string numeroFatturaPrincipaleField;

        private DateTime dataFatturaPrincipaleField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroFatturaPrincipale
        {
            get
            {
                return this.numeroFatturaPrincipaleField;
            }
            set
            {
                this.numeroFatturaPrincipaleField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataFatturaPrincipale
        {
            get
            {
                return this.dataFatturaPrincipaleField;
            }
            set
            {
                this.dataFatturaPrincipaleField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiAnagraficiVettoreType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private AnagraficaType anagraficaField;

        private string numeroLicenzaGuidaField;

        
        
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        
        
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        
        
        public AnagraficaType Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroLicenzaGuida
        {
            get
            {
                return this.numeroLicenzaGuidaField;
            }
            set
            {
                this.numeroLicenzaGuidaField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class AnagraficaType
    {

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string titoloField;

        private string codEORIField;

        
        [XmlElement( "Cognome", typeof( string ),  DataType = "normalizedString" )]
        [XmlElement( "Denominazione", typeof( string ),  DataType = "normalizedString" )]
        [XmlElement( "Nome", typeof( string ),  DataType = "normalizedString" )]
        [XmlChoiceIdentifier( "ItemsElementName" )]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        
        [XmlElement( "ItemsElementName" )]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Titolo
        {
            get
            {
                return this.titoloField;
            }
            set
            {
                this.titoloField = value;
            }
        }

        
        
        public string CodEORI
        {
            get
            {
                return this.codEORIField;
            }
            set
            {
                this.codEORIField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1", IncludeInSchema = false )]
    public enum ItemsChoiceType
    {

        
        [XmlEnum( ":Cognome" )]
        Cognome,

        
        [XmlEnum( ":Denominazione" )]
        Denominazione,

        
        [XmlEnum( ":Nome" )]
        Nome,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiTrasportoType
    {

        private DatiAnagraficiVettoreType datiAnagraficiVettoreField;

        private string mezzoTrasportoField;

        private string causaleTrasportoField;

        private string numeroColliField;

        private string descrizioneField;

        private string unitaMisuraPesoField;

        private decimal pesoLordoField;

        private bool pesoLordoFieldSpecified;

        private decimal pesoNettoField;

        private bool pesoNettoFieldSpecified;

        private DateTime dataOraRitiroField;

        private bool dataOraRitiroFieldSpecified;

        private DateTime dataInizioTrasportoField;

        private bool dataInizioTrasportoFieldSpecified;

        private string tipoResaField;

        private IndirizzoType indirizzoResaField;

        private DateTime dataOraConsegnaField;

        private bool dataOraConsegnaFieldSpecified;

        
        
        public DatiAnagraficiVettoreType DatiAnagraficiVettore
        {
            get
            {
                return this.datiAnagraficiVettoreField;
            }
            set
            {
                this.datiAnagraficiVettoreField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string MezzoTrasporto
        {
            get
            {
                return this.mezzoTrasportoField;
            }
            set
            {
                this.mezzoTrasportoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CausaleTrasporto
        {
            get
            {
                return this.causaleTrasportoField;
            }
            set
            {
                this.causaleTrasportoField = value;
            }
        }

        
        [XmlElement(  DataType = "integer" )]
        public string NumeroColli
        {
            get
            {
                return this.numeroColliField;
            }
            set
            {
                this.numeroColliField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string UnitaMisuraPeso
        {
            get
            {
                return this.unitaMisuraPesoField;
            }
            set
            {
                this.unitaMisuraPesoField = value;
            }
        }

        
        
        public decimal PesoLordo
        {
            get
            {
                return this.pesoLordoField;
            }
            set
            {
                this.pesoLordoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool PesoLordoSpecified
        {
            get
            {
                return this.pesoLordoFieldSpecified;
            }
            set
            {
                this.pesoLordoFieldSpecified = value;
            }
        }

        
        
        public decimal PesoNetto
        {
            get
            {
                return this.pesoNettoField;
            }
            set
            {
                this.pesoNettoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool PesoNettoSpecified
        {
            get
            {
                return this.pesoNettoFieldSpecified;
            }
            set
            {
                this.pesoNettoFieldSpecified = value;
            }
        }

        
        
        public DateTime DataOraRitiro
        {
            get
            {
                return this.dataOraRitiroField;
            }
            set
            {
                this.dataOraRitiroField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataOraRitiroSpecified
        {
            get
            {
                return this.dataOraRitiroFieldSpecified;
            }
            set
            {
                this.dataOraRitiroFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataInizioTrasporto
        {
            get
            {
                return this.dataInizioTrasportoField;
            }
            set
            {
                this.dataInizioTrasportoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataInizioTrasportoSpecified
        {
            get
            {
                return this.dataInizioTrasportoFieldSpecified;
            }
            set
            {
                this.dataInizioTrasportoFieldSpecified = value;
            }
        }

        
        
        public string TipoResa
        {
            get
            {
                return this.tipoResaField;
            }
            set
            {
                this.tipoResaField = value;
            }
        }

        
        
        public IndirizzoType IndirizzoResa
        {
            get
            {
                return this.indirizzoResaField;
            }
            set
            {
                this.indirizzoResaField = value;
            }
        }

        
        
        public DateTime DataOraConsegna
        {
            get
            {
                return this.dataOraConsegnaField;
            }
            set
            {
                this.dataOraConsegnaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataOraConsegnaSpecified
        {
            get
            {
                return this.dataOraConsegnaFieldSpecified;
            }
            set
            {
                this.dataOraConsegnaFieldSpecified = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class IndirizzoType
    {

        private string indirizzoField;

        private string numeroCivicoField;

        private string cAPField;

        private string comuneField;

        private string provinciaField;

        private string nazioneField;

        public IndirizzoType()
        {
            this.nazioneField = "IT";
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Indirizzo
        {
            get
            {
                return this.indirizzoField;
            }
            set
            {
                this.indirizzoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroCivico
        {
            get
            {
                return this.numeroCivicoField;
            }
            set
            {
                this.numeroCivicoField = value;
            }
        }

        
        
        public string CAP
        {
            get
            {
                return this.cAPField;
            }
            set
            {
                this.cAPField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Comune
        {
            get
            {
                return this.comuneField;
            }
            set
            {
                this.comuneField = value;
            }
        }

        
        
        public string Provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }

        
        
        public string Nazione
        {
            get
            {
                return this.nazioneField;
            }
            set
            {
                this.nazioneField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiDDTType
    {

        private string numeroDDTField;

        private DateTime dataDDTField;

        private string[] riferimentoNumeroLineaField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroDDT
        {
            get
            {
                return this.numeroDDTField;
            }
            set
            {
                this.numeroDDTField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataDDT
        {
            get
            {
                return this.dataDDTField;
            }
            set
            {
                this.dataDDTField = value;
            }
        }

        
        [XmlElement( "RiferimentoNumeroLinea",  DataType = "integer" )]
        public string[] RiferimentoNumeroLinea
        {
            get
            {
                return this.riferimentoNumeroLineaField;
            }
            set
            {
                this.riferimentoNumeroLineaField = value;
            }
        }
    }
    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiSALType
    {

        private string riferimentoFaseField;

        
        [XmlElement(  DataType = "integer" )]
        public string RiferimentoFase
        {
            get
            {
                return this.riferimentoFaseField;
            }
            set
            {
                this.riferimentoFaseField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiDocumentiCorrelatiType
    {

        private string[] riferimentoNumeroLineaField;

        private string idDocumentoField;

        private DateTime dataField;

        private bool dataFieldSpecified;

        private string numItemField;

        private string codiceCommessaConvenzioneField;

        private string codiceCUPField;

        private string codiceCIGField;

        
        [XmlElement( "RiferimentoNumeroLinea",  DataType = "integer" )]
        public string[] RiferimentoNumeroLinea
        {
            get
            {
                return this.riferimentoNumeroLineaField;
            }
            set
            {
                this.riferimentoNumeroLineaField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string IdDocumento
        {
            get
            {
                return this.idDocumentoField;
            }
            set
            {
                this.idDocumentoField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataSpecified
        {
            get
            {
                return this.dataFieldSpecified;
            }
            set
            {
                this.dataFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumItem
        {
            get
            {
                return this.numItemField;
            }
            set
            {
                this.numItemField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodiceCommessaConvenzione
        {
            get
            {
                return this.codiceCommessaConvenzioneField;
            }
            set
            {
                this.codiceCommessaConvenzioneField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodiceCUP
        {
            get
            {
                return this.codiceCUPField;
            }
            set
            {
                this.codiceCUPField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string CodiceCIG
        {
            get
            {
                return this.codiceCIGField;
            }
            set
            {
                this.codiceCIGField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiCassaPrevidenzialeType
    {

        private TipoCassaType tipoCassaField;

        private decimal alCassaField;

        private decimal importoContributoCassaField;

        private decimal imponibileCassaField;

        private bool imponibileCassaFieldSpecified;

        private decimal aliquotaIVAField;

        private RitenutaType ritenutaField;

        private bool ritenutaFieldSpecified;

        private NaturaType naturaField;

        private bool naturaFieldSpecified;

        private string riferimentoAmministrazioneField;

        
        
        public TipoCassaType TipoCassa
        {
            get
            {
                return this.tipoCassaField;
            }
            set
            {
                this.tipoCassaField = value;
            }
        }

        
        
        public decimal AlCassa
        {
            get
            {
                return this.alCassaField;
            }
            set
            {
                this.alCassaField = value;
            }
        }

        
        
        public decimal ImportoContributoCassa
        {
            get
            {
                return this.importoContributoCassaField;
            }
            set
            {
                this.importoContributoCassaField = value;
            }
        }

        
        
        public decimal ImponibileCassa
        {
            get
            {
                return this.imponibileCassaField;
            }
            set
            {
                this.imponibileCassaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ImponibileCassaSpecified
        {
            get
            {
                return this.imponibileCassaFieldSpecified;
            }
            set
            {
                this.imponibileCassaFieldSpecified = value;
            }
        }

        
        
        public decimal AliquotaIVA
        {
            get
            {
                return this.aliquotaIVAField;
            }
            set
            {
                this.aliquotaIVAField = value;
            }
        }

        
        
        public RitenutaType Ritenuta
        {
            get
            {
                return this.ritenutaField;
            }
            set
            {
                this.ritenutaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool RitenutaSpecified
        {
            get
            {
                return this.ritenutaFieldSpecified;
            }
            set
            {
                this.ritenutaFieldSpecified = value;
            }
        }

        
        
        public NaturaType Natura
        {
            get
            {
                return this.naturaField;
            }
            set
            {
                this.naturaField = value;
            }
        }

        
        [XmlIgnore()]
        public bool NaturaSpecified
        {
            get
            {
                return this.naturaFieldSpecified;
            }
            set
            {
                this.naturaFieldSpecified = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string RiferimentoAmministrazione
        {
            get
            {
                return this.riferimentoAmministrazioneField;
            }
            set
            {
                this.riferimentoAmministrazioneField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum TipoCassaType
    {

        
        TC01,

        
        TC02,

        
        TC03,

        
        TC04,

        
        TC05,

        
        TC06,

        
        TC07,

        
        TC08,

        
        TC09,

        
        TC10,

        
        TC11,

        
        TC12,

        
        TC13,

        
        TC14,

        
        TC15,

        
        TC16,

        
        TC17,

        
        TC18,

        
        TC19,

        
        TC20,

        
        TC21,

        
        TC22,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiBolloType
    {

        private BolloVirtualeType bolloVirtualeField;

        private decimal importoBolloField;

        
        
        public BolloVirtualeType BolloVirtuale
        {
            get
            {
                return this.bolloVirtualeField;
            }
            set
            {
                this.bolloVirtualeField = value;
            }
        }

        
        
        public decimal ImportoBollo
        {
            get
            {
                return this.importoBolloField;
            }
            set
            {
                this.importoBolloField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum BolloVirtualeType
    {

        
        SI,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiRitenutaType
    {

        private TipoRitenutaType tipoRitenutaField;

        private decimal importoRitenutaField;

        private decimal aliquotaRitenutaField;

        private CausalePagamentoType causalePagamentoField;

        
        
        public TipoRitenutaType TipoRitenuta
        {
            get
            {
                return this.tipoRitenutaField;
            }
            set
            {
                this.tipoRitenutaField = value;
            }
        }

        
        
        public decimal ImportoRitenuta
        {
            get
            {
                return this.importoRitenutaField;
            }
            set
            {
                this.importoRitenutaField = value;
            }
        }

        
        
        public decimal AliquotaRitenuta
        {
            get
            {
                return this.aliquotaRitenutaField;
            }
            set
            {
                this.aliquotaRitenutaField = value;
            }
        }

        
        
        public CausalePagamentoType CausalePagamento
        {
            get
            {
                return this.causalePagamentoField;
            }
            set
            {
                this.causalePagamentoField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum TipoRitenutaType
    {

        
        RT01,

        
        RT02,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum CausalePagamentoType
    {

        
        A,

        
        B,

        
        C,

        
        D,

        
        E,

        
        G,

        
        H,

        
        I,

        
        L,

        
        M,

        
        N,

        
        O,

        
        P,

        
        Q,

        
        R,

        
        S,

        
        T,

        
        U,

        
        V,

        
        W,

        
        X,

        
        Y,

        
        Z,

        
        L1,

        
        M1,

        
        O1,

        
        V1,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiGeneraliDocumentoType
    {

        private TipoDocumentoType tipoDocumentoField;

        private string divisaField;

        private DateTime dataField;

        private string numeroField;

        private DatiRitenutaType datiRitenutaField;

        private DatiBolloType datiBolloField;

        private DatiCassaPrevidenzialeType[] datiCassaPrevidenzialeField;

        private ScontoMaggiorazioneType[] scontoMaggiorazioneField;

        private decimal importoTotaleDocumentoField;

        private bool importoTotaleDocumentoFieldSpecified;

        private decimal arrotondamentoField;

        private bool arrotondamentoFieldSpecified;

        private string[] causaleField;

        private Art73Type art73Field;

        private bool art73FieldSpecified;

        
        
        public TipoDocumentoType TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }

        
        
        public string Divisa
        {
            get
            {
                return this.divisaField;
            }
            set
            {
                this.divisaField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }

        
        
        public DatiRitenutaType DatiRitenuta
        {
            get
            {
                return this.datiRitenutaField;
            }
            set
            {
                this.datiRitenutaField = value;
            }
        }

        
        
        public DatiBolloType DatiBollo
        {
            get
            {
                return this.datiBolloField;
            }
            set
            {
                this.datiBolloField = value;
            }
        }

        
        [XmlElement( "DatiCassaPrevidenziale", Form = XmlSchemaForm.Unqualified )]
        public DatiCassaPrevidenzialeType[] DatiCassaPrevidenziale
        {
            get
            {
                return this.datiCassaPrevidenzialeField;
            }
            set
            {
                this.datiCassaPrevidenzialeField = value;
            }
        }

        
        [XmlElement( "ScontoMaggiorazione", Form = XmlSchemaForm.Unqualified )]
        public ScontoMaggiorazioneType[] ScontoMaggiorazione
        {
            get
            {
                return this.scontoMaggiorazioneField;
            }
            set
            {
                this.scontoMaggiorazioneField = value;
            }
        }

        
        
        public decimal ImportoTotaleDocumento
        {
            get
            {
                return this.importoTotaleDocumentoField;
            }
            set
            {
                this.importoTotaleDocumentoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ImportoTotaleDocumentoSpecified
        {
            get
            {
                return this.importoTotaleDocumentoFieldSpecified;
            }
            set
            {
                this.importoTotaleDocumentoFieldSpecified = value;
            }
        }

        
        
        public decimal Arrotondamento
        {
            get
            {
                return this.arrotondamentoField;
            }
            set
            {
                this.arrotondamentoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool ArrotondamentoSpecified
        {
            get
            {
                return this.arrotondamentoFieldSpecified;
            }
            set
            {
                this.arrotondamentoFieldSpecified = value;
            }
        }

        
        [XmlElement( "Causale",  DataType = "normalizedString" )]
        public string[] Causale
        {
            get
            {
                return this.causaleField;
            }
            set
            {
                this.causaleField = value;
            }
        }

        
        
        public Art73Type Art73
        {
            get
            {
                return this.art73Field;
            }
            set
            {
                this.art73Field = value;
            }
        }

        
        [XmlIgnore()]
        public bool Art73Specified
        {
            get
            {
                return this.art73FieldSpecified;
            }
            set
            {
                this.art73FieldSpecified = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum TipoDocumentoType
    {

        
        TD01,

        
        TD02,

        
        TD03,

        
        TD04,

        
        TD05,

        
        TD06,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum Art73Type
    {

        
        SI,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiGeneraliType
    {

        private DatiGeneraliDocumentoType datiGeneraliDocumentoField;
        private DatiDocumentiCorrelatiType[] datiOrdineAcquistoField;
        private DatiDocumentiCorrelatiType[] datiContrattoField;
        private DatiDocumentiCorrelatiType[] datiConvenzioneField;
        private DatiDocumentiCorrelatiType[] datiRicezioneField;
        private DatiDocumentiCorrelatiType[] datiFattureCollegateField;
        private DatiSALType[] datiSALField;
        private DatiDDTType[] datiDDTField;
        private DatiTrasportoType datiTrasportoField;
        private FatturaPrincipaleType fatturaPrincipaleField;
        
        
        public DatiGeneraliDocumentoType DatiGeneraliDocumento
        {
            get
            {
                return this.datiGeneraliDocumentoField;
            }
            set
            {
                this.datiGeneraliDocumentoField = value;
            }
        }
        
        [XmlElement( "DatiOrdineAcquisto", Form = XmlSchemaForm.Unqualified )]
        public DatiDocumentiCorrelatiType[] DatiOrdineAcquisto
        {
            get
            {
                return this.datiOrdineAcquistoField;
            }
            set
            {
                this.datiOrdineAcquistoField = value;
            }
        }
        
        [XmlElement( "DatiContratto", Form = XmlSchemaForm.Unqualified )]
        public DatiDocumentiCorrelatiType[] DatiContratto
        {
            get
            {
                return this.datiContrattoField;
            }
            set
            {
                this.datiContrattoField = value;
            }
        }
        
        [XmlElement( "DatiConvenzione", Form = XmlSchemaForm.Unqualified )]
        public DatiDocumentiCorrelatiType[] DatiConvenzione
        {
            get
            {
                return this.datiConvenzioneField;
            }
            set
            {
                this.datiConvenzioneField = value;
            }
        }
        
        [XmlElement( "DatiRicezione", Form = XmlSchemaForm.Unqualified )]
        public DatiDocumentiCorrelatiType[] DatiRicezione
        {
            get
            {
                return this.datiRicezioneField;
            }
            set
            {
                this.datiRicezioneField = value;
            }
        }
        
        [XmlElement( "DatiFattureCollegate", Form = XmlSchemaForm.Unqualified )]
        public DatiDocumentiCorrelatiType[] DatiFattureCollegate
        {
            get
            {
                return this.datiFattureCollegateField;
            }
            set
            {
                this.datiFattureCollegateField = value;
            }
        }
        
        [XmlElement( "DatiSAL", Form = XmlSchemaForm.Unqualified )]
        public DatiSALType[] DatiSAL
        {
            get
            {
                return this.datiSALField;
            }
            set
            {
                this.datiSALField = value;
            }
        }
        
        [XmlElement( "DatiDDT", Form = XmlSchemaForm.Unqualified )]
        public DatiDDTType[] DatiDDT
        {
            get
            {
                return this.datiDDTField;
            }
            set
            {
                this.datiDDTField = value;
            }
        }
        
        public DatiTrasportoType DatiTrasporto
        {
            get
            {
                return this.datiTrasportoField;
            }
            set
            {
                this.datiTrasportoField = value;
            }
        }
        
        public FatturaPrincipaleType FatturaPrincipale
        {
            get
            {
                return this.fatturaPrincipaleField;
            }
            set
            {
                this.fatturaPrincipaleField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class FatturaElettronicaBodyType
    {

        private DatiGeneraliType datiGeneraliField;

        private DatiBeniServiziType datiBeniServiziField;

        private DatiVeicoliType datiVeicoliField;

        private DatiPagamentoType[] datiPagamentoField;

        private AllegatiType[] allegatiField;

        
        
        public DatiGeneraliType DatiGenerali
        {
            get
            {
                return this.datiGeneraliField;
            }
            set
            {
                this.datiGeneraliField = value;
            }
        }

        
        
        public DatiBeniServiziType DatiBeniServizi
        {
            get
            {
                return this.datiBeniServiziField;
            }
            set
            {
                this.datiBeniServiziField = value;
            }
        }

        
        
        public DatiVeicoliType DatiVeicoli
        {
            get
            {
                return this.datiVeicoliField;
            }
            set
            {
                this.datiVeicoliField = value;
            }
        }

        
        [XmlElement( "DatiPagamento", Form = XmlSchemaForm.Unqualified )]
        public DatiPagamentoType[] DatiPagamento
        {
            get
            {
                return this.datiPagamentoField;
            }
            set
            {
                this.datiPagamentoField = value;
            }
        }

        
        [XmlElement( "Allegati", Form = XmlSchemaForm.Unqualified )]
        public AllegatiType[] Allegati
        {
            get
            {
                return this.allegatiField;
            }
            set
            {
                this.allegatiField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiAnagraficiTerzoIntermediarioType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private AnagraficaType anagraficaField;

        
        
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        
        
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        
        
        public AnagraficaType Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class TerzoIntermediarioSoggettoEmittenteType
    {

        private DatiAnagraficiTerzoIntermediarioType datiAnagraficiField;

        
        
        public DatiAnagraficiTerzoIntermediarioType DatiAnagrafici
        {
            get
            {
                return this.datiAnagraficiField;
            }
            set
            {
                this.datiAnagraficiField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiAnagraficiCessionarioType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private AnagraficaType anagraficaField;

        
        
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        
        
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        
        
        public AnagraficaType Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class CessionarioCommittenteType
    {

        private DatiAnagraficiCessionarioType datiAnagraficiField;

        private IndirizzoType sedeField;

        
        
        public DatiAnagraficiCessionarioType DatiAnagrafici
        {
            get
            {
                return this.datiAnagraficiField;
            }
            set
            {
                this.datiAnagraficiField = value;
            }
        }

        
        
        public IndirizzoType Sede
        {
            get
            {
                return this.sedeField;
            }
            set
            {
                this.sedeField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiAnagraficiRappresentanteType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private AnagraficaType anagraficaField;

        
        
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        
        
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        
        
        public AnagraficaType Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class RappresentanteFiscaleType
    {

        private DatiAnagraficiRappresentanteType datiAnagraficiField;

        
        
        public DatiAnagraficiRappresentanteType DatiAnagrafici
        {
            get
            {
                return this.datiAnagraficiField;
            }
            set
            {
                this.datiAnagraficiField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class ContattiType
    {

        private string telefonoField;

        private string faxField;

        private string emailField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }

        
        
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class IscrizioneREAType
    {

        private string ufficioField;

        private string numeroREAField;

        private decimal capitaleSocialeField;

        private bool capitaleSocialeFieldSpecified;

        private SocioUnicoType socioUnicoField;

        private bool socioUnicoFieldSpecified;

        private StatoLiquidazioneType statoLiquidazioneField;

        
        
        public string Ufficio
        {
            get
            {
                return this.ufficioField;
            }
            set
            {
                this.ufficioField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroREA
        {
            get
            {
                return this.numeroREAField;
            }
            set
            {
                this.numeroREAField = value;
            }
        }

        
        
        public decimal CapitaleSociale
        {
            get
            {
                return this.capitaleSocialeField;
            }
            set
            {
                this.capitaleSocialeField = value;
            }
        }

        
        [XmlIgnore()]
        public bool CapitaleSocialeSpecified
        {
            get
            {
                return this.capitaleSocialeFieldSpecified;
            }
            set
            {
                this.capitaleSocialeFieldSpecified = value;
            }
        }

        
        
        public SocioUnicoType SocioUnico
        {
            get
            {
                return this.socioUnicoField;
            }
            set
            {
                this.socioUnicoField = value;
            }
        }

        
        [XmlIgnore()]
        public bool SocioUnicoSpecified
        {
            get
            {
                return this.socioUnicoFieldSpecified;
            }
            set
            {
                this.socioUnicoFieldSpecified = value;
            }
        }

        
        
        public StatoLiquidazioneType StatoLiquidazione
        {
            get
            {
                return this.statoLiquidazioneField;
            }
            set
            {
                this.statoLiquidazioneField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum SocioUnicoType
    {

        
        SU,

        
        SM,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum StatoLiquidazioneType
    {

        
        LS,

        
        LN,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class DatiAnagraficiCedenteType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private AnagraficaType anagraficaField;

        private string alboProfessionaleField;

        private string provinciaAlboField;

        private string numeroIscrizioneAlboField;

        private DateTime dataIscrizioneAlboField;

        private bool dataIscrizioneAlboFieldSpecified;

        private RegimeFiscaleType regimeFiscaleField;

        
        
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        
        
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        
        
        public AnagraficaType Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string AlboProfessionale
        {
            get
            {
                return this.alboProfessionaleField;
            }
            set
            {
                this.alboProfessionaleField = value;
            }
        }

        
        
        public string ProvinciaAlbo
        {
            get
            {
                return this.provinciaAlboField;
            }
            set
            {
                this.provinciaAlboField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string NumeroIscrizioneAlbo
        {
            get
            {
                return this.numeroIscrizioneAlboField;
            }
            set
            {
                this.numeroIscrizioneAlboField = value;
            }
        }

        
        [XmlElement(  DataType = "date" )]
        public DateTime DataIscrizioneAlbo
        {
            get
            {
                return this.dataIscrizioneAlboField;
            }
            set
            {
                this.dataIscrizioneAlboField = value;
            }
        }

        
        [XmlIgnore()]
        public bool DataIscrizioneAlboSpecified
        {
            get
            {
                return this.dataIscrizioneAlboFieldSpecified;
            }
            set
            {
                this.dataIscrizioneAlboFieldSpecified = value;
            }
        }

        
        
        public RegimeFiscaleType RegimeFiscale
        {
            get
            {
                return this.regimeFiscaleField;
            }
            set
            {
                this.regimeFiscaleField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum RegimeFiscaleType
    {

        
        RF01,

        
        RF02,

        
        RF03,

        
        RF04,

        
        RF05,

        
        RF06,

        
        RF07,

        
        RF08,

        
        RF09,

        
        RF10,

        
        RF11,

        
        RF12,

        
        RF13,

        
        RF14,

        
        RF15,

        
        RF16,

        
        RF17,

        
        RF19,

        
        RF18,
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class CedentePrestatoreType
    {

        private DatiAnagraficiCedenteType datiAnagraficiField;

        private IndirizzoType sedeField;

        private IndirizzoType stabileOrganizzazioneField;

        private IscrizioneREAType iscrizioneREAField;

        private ContattiType contattiField;

        private string riferimentoAmministrazioneField;

        
        
        public DatiAnagraficiCedenteType DatiAnagrafici
        {
            get
            {
                return this.datiAnagraficiField;
            }
            set
            {
                this.datiAnagraficiField = value;
            }
        }

        
        
        public IndirizzoType Sede
        {
            get
            {
                return this.sedeField;
            }
            set
            {
                this.sedeField = value;
            }
        }

        
        
        public IndirizzoType StabileOrganizzazione
        {
            get
            {
                return this.stabileOrganizzazioneField;
            }
            set
            {
                this.stabileOrganizzazioneField = value;
            }
        }

        
        
        public IscrizioneREAType IscrizioneREA
        {
            get
            {
                return this.iscrizioneREAField;
            }
            set
            {
                this.iscrizioneREAField = value;
            }
        }

        
        
        public ContattiType Contatti
        {
            get
            {
                return this.contattiField;
            }
            set
            {
                this.contattiField = value;
            }
        }

        
        [XmlElement(  DataType = "normalizedString" )]
        public string RiferimentoAmministrazione
        {
            get
            {
                return this.riferimentoAmministrazioneField;
            }
            set
            {
                this.riferimentoAmministrazioneField = value;
            }
        }
    }

    
    
    [Serializable()]
    

    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public partial class ContattiTrasmittenteType
    {

        private string telefonoField;

        private string emailField;

        
        [XmlElement(  DataType = "normalizedString" )]
        public string Telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }

        
        
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum FormatoTrasmissioneType
    {

        
        SDI11,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum SoggettoEmittenteType
    {

        
        CC,

        
        TZ,
    }

    
    
    [Serializable()]
    [XmlType( Namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1" )]
    public enum VersioneSchemaType
    {

        
        [XmlEnum( "1.1" )]
        Item11,
    }
}
